export const ActionType = {
    UPDATE_LEVEL_STAGE : 'UPDATE_LEVEL_STAGE',

    //prompt generation
    UPDATE_PROMPT_DATA: 'UPDATE_PROMPT_DATA',
    SET_THEME_DATA: 'SET_THEME_DATA',
    SET_REQ_TIME: 'SET_REQ_TIME',

    //product
    PRODUCT_VIEW_SWITCH: 'PRODUCT_VIEW_SWITCH',
    PRODUCT_ATTRIBUTE: 'PRODUCT_ATTRIBUTE',
    PRODUCT_COLOR: 'PRODUCT_COLOR',

}