module.exports = Object.freeze({
	STATUS: ["ACTIVE", "INACTIVE", "BLOCKED", "DELETED"],
	RELATION: [
		"SELF",
		"FATHER",
		"MOTHER",
		"WIFE",
		"HUSBAND",
		"SON",
		"DAUGHTER",
		"OTHER",
		"BROTHER",
		"SISTER",
		"SPOUSE",
		"Self",
		"Father",
		"Mother",
		"Wife",
		"Husband",
		"Son",
		"Daughter",
		"Other",
		"Brother",
		"Sister",
		"Spouse",
	],
	GENDER: ["MALE", "FEMALE", "OTHER", "Male", "Female", "Other"],
});
